// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkllkcopiwpvirvzxiin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprbGxrY29waXdwdmlydnp4aWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTY3NzQsImV4cCI6MjA2OTc3Mjc3NH0.b6q5jOh6V9uBPLJCKRofkHNGWmtA5xCHP2r8I152Y84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});